export const VIDEO_LIST = 'swiper/VIDEO_LIST'
export const CHANNEL_LIST = 'swiper/CHANNEL_LIST'
export const CHOSE_CHANNEL = 'swiper/CHOSE_CHANNEL'
export const CHANGE_ACTIONTYPE = 'swiper/CHANGE_ACTIONTYPE'
export const PULL_STATE = 'swiper/PULL_STATE'